name: release
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      ARTIFACT_REGISTRY_USER: ${{ secrets.ARTIFACT_REGISTRY_USER }}
      ARTIFACT_REGISTRY_PASSWORD: ${{ secrets.ARTIFACT_REGISTRY_PASSWORD }}
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: make run-test
      - run: if [ ! -z "$SONAR_HOST_URL" ]; then bash -c "make quality-analysis"; fi
      - run: make deploy-package